"""
Django settings for tourist_system project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)lxsj^@wa#1#1*-z0q1+k(9#re0^!ard0fo38__g*xvuxz(&6p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'tourOrderingApp', 
    'django_nvd3',
    'django_light',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',   
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tourOrderingApp.LoginCheckMiddleWare.LoginCheckMiddleWare',
]

ROOT_URLCONF = 'tourist_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tourist_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE':'django.db.backends.mysql',
        'NAME':'Tourist',
        'USER':'root',
        'PASSWORD':'m2r3i4s8',            
        'HOST':'localhost',
        'PORT':'3307',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

AUTH_USER_MODEL = 'tourOrderingApp.CustomUser'
AUTHENTICATION_BACKENDS = ['tourOrderingApp.emailBackEnd.EmailBackend']
# EMAIL_BACKEND = "django.core.mail.backends.bdtvjjdagryvnqeb.filebased.EmailBackend"
# EMAIL_FILE_PATH = os.path.join(BASE_DIR,"sent_emails")
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'mrishohamisi1998@gmail.com'
EMAIL_HOST_PASSWORD = 'rtnwirbujomgbjsh'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR,"media")


STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR,"static")
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    # Title of the window
    "site_title": "Zan Trip & Tours",

    # Title on the login screen
    "site_header": "Zan Trip & Tours",

    # Title on the brand
    "site_brand": "Zan Trip & Tours",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "images/ZanTrip.jpg",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to Zan Trip & Tours",

    # CSS classes that are applied to the logo
    "site_logo_classes": "img-circle",

    # Copyright on the footer
    "copyright": "Zan Trip & Tours Ltd",

    # Relative path to a favicon for your site
    "site_icon": None,

    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home",  "url": "admin_dashboard"},
        {"name": "Support", "url": "tour_category_list", "new_window": False},
        {"model": "tourist.Tourist"},

    ],

    # Additional links to include in the user menu on the top right
    "usermenu_links": [
        {"name": "Support", "url": "activity_list", "new_window": False},
    ],

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to auto-expand the menu
    "navigation_expanded": True,

    # Hide these models when generating side menu
    "hide_models": [],
    
     # Custom links to append to app groups with dropdown menu links
    "custom_links": {
        "tourOrderingApp": [
            {
                "name": "Bookings",
                "url": "save_tour_package",
                "icon": "fas fa-calendar-check",
                "children": [
                    {"name": "View Bookings", "url": "bookings"},
                    {"name": "Add Booking", "url": "add_booking"},
                ],
            },
            {
                "name": "Payments",
                "url": "save_transportation",
                "icon": "fas fa-money-bill-wave",
                "children": [
                    {"name": "View Payments", "url": "delete_tour_category"},
                    {"name": "Add Payment", "url": "add_payment"},
                ],
            },
        ],
    },
    
    # Custom icons for side menu apps/models
    "icons": {
        # Auth app icons
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        # Admin app icons
        "admin.LogEntry": "fas fa-file",

        # TourOrderingApp icons
        "tourOrderingApp.Invoice": "fas fa-file-invoice",
        "tourOrderingApp.Review": "fas fa-star",
        "tourOrderingApp.Booking": "fas fa-calendar-check",
        "tourOrderingApp.Payment": "fas fa-money-bill-wave",
        "tourOrderingApp.TourPackage": "fas fa-suitcase",
        "tourOrderingApp.Activity": "fas fa-hiking",
        "tourOrderingApp.Transportation": "fas fa-bus",
        "tourOrderingApp.TourCategory": "fas fa-map-signs",
        "tourOrderingApp.Tourist": "fas fa-user",
        "tourOrderingApp.Country": "fas fa-globe",
        "tourOrderingApp.AdminHOD": "fas fa-user-tie",
    },

    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",
    # Order apps automatically, but make sure choice and book admin links are first within the books app
   "order_with_respect_to": ["tourOrderingApp.TourPackage", "tourOrderingApp.Country"],
   
    # Render out the change view as a single form, or in tabs
    "changeform_format": "horizontal_tabs",

    # Add a language dropdown into the admin
    "language_chooser": True,

    # Relative paths to custom CSS/JS scripts
    "custom_css": None,
    "custom_js": None,

    # Whether to link font from fonts.googleapis.com
    "use_google_fonts_cdn": True,

    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
}
JAZZMIN_SETTINGS["show_ui_builder"] = True
JAZZMIN_UI_TWEAKS = {  
    "theme": "flatly",
    "dark_mode_theme": "slate",
}