# Generated by Django 4.2.11 on 2024-04-17 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0002_remove_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourOrderingApp.country'),
        ),
    ]
