# Generated by Django 4.2.11 on 2024-04-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0003_alter_tourist_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourOrderingApp.country'),
        ),
    ]
