# Generated by Django 4.2.11 on 2024-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0004_alter_tourist_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
