# Generated by Django 4.2.11 on 2024-04-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0006_transportation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
