# Generated by Django 4.2.11 on 2024-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0007_alter_transportation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='availability',
            field=models.CharField(max_length=50),
        ),
    ]
