# Generated by Django 4.2.11 on 2024-04-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0010_alter_activity_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration_hours',
            field=models.CharField(max_length=20),
        ),
    ]
