# Generated by Django 4.2.11 on 2024-05-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0013_contactus_hotel_remove_tourist_special_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourOrderingApp.country'),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
