# Generated by Django 4.2.11 on 2024-05-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0015_transport_transportbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportbooking',
            name='hotel',
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='transport_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourOrderingApp.transport'),
        ),
    ]
