# Generated by Django 4.2.11 on 2024-06-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0020_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tour_package',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tourist',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tourist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tour_package',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tourist',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='transportation_options',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='TourCategory',
        ),
        migrations.DeleteModel(
            name='Tourist',
        ),
        migrations.DeleteModel(
            name='TourPackage',
        ),
    ]
