# Generated by Django 4.2.11 on 2024-06-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourOrderingApp', '0022_hotelbooking_is_active_transportbooking_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transportbooking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
